
```{r}
library(tidyverse)
library(readxl)
```

```{r}
stock2018 <- read_excel("./bda2020_dataset/stock_data.xlsx", sheet = 2)
```

```{r}
stock2018_df <- stock2018 %>% filter(證券代碼 == "Y9999 加權指數") %>%
  select(證券代碼, 年月日, "開盤價" = 3, "收盤價" = 6) %>%
  mutate("股價變化" = 收盤價 - 開盤價) %>%
  mutate("五天後" = lag(收盤價, 5)) %>%
  mutate("三天後" = lag(收盤價, 3)) %>%
  mutate("十天後" = lag(收盤價, 10)) %>%
  mutate("五天後變化" = 五天後 - 收盤價) %>%
  mutate("三天後變化" = 三天後 - 收盤價) %>%
  mutate("十天後變化" = 十天後 - 收盤價) %>%
  mutate("五天後漲" = if_else(五天後變化 >=0, 1, 0)) %>%
  mutate("三天後漲" = if_else(三天後變化 >=0, 1, 0)) %>%
  mutate("十天後漲" = if_else(十天後變化 >=0, 1, 0)) %>%
  view()
```

```{r}
stock2017 <- read_excel("./bda2020_dataset/stock_data.xlsx", sheet = 3)
stock2016 <- read_excel("./bda2020_dataset/stock_data.xlsx", sheet = 4)
```

```{r}
stock2017_df <- stock2017 %>% filter(證券代碼 == "Y9999 加權指數") %>%
  select(證券代碼, 年月日, "開盤價" = 3, "收盤價" = 6) %>%
  mutate("股價變化" = 收盤價 - 開盤價) %>%
  mutate("五天後" = lag(收盤價, 5)) %>%
  mutate("三天後" = lag(收盤價, 3)) %>%
  mutate("十天後" = lag(收盤價, 10))

stock2017_df$五天後[1:5] = stock2018_df$收盤價[243:247]
stock2017_df$三天後[1:3] = stock2018_df$收盤價[245:247]
stock2017_df$十天後[1:10] = stock2018_df$收盤價[238:247]

stock2017_df <- stock2017_df %>%
  mutate("五天後變化" = 五天後 - 收盤價) %>%
  mutate("三天後變化" = 三天後 - 收盤價) %>%
  mutate("十天後變化" = 十天後 - 收盤價) %>%
  mutate("五天後漲" = if_else(五天後變化 >=0, 1, 0)) %>%
  mutate("三天後漲" = if_else(三天後變化 >=0, 1, 0)) %>%
  mutate("十天後漲" = if_else(十天後變化 >=0, 1, 0)) %>%
  view()
```

```{r}
stock2016_df <- stock2016 %>% filter(證券代碼 == "Y9999 加權指數") %>%
  select(證券代碼, 年月日, "開盤價" = 3, "收盤價" = 6) %>%
  mutate("股價變化" = 收盤價 - 開盤價) %>%
  mutate("五天後" = lag(收盤價, 5)) %>%
  mutate("三天後" = lag(收盤價, 3)) %>%
  mutate("十天後" = lag(收盤價, 10))
  
stock2016_df$五天後[1:5] = stock2017_df$收盤價[242:246]
stock2016_df$三天後[1:3] = stock2017_df$收盤價[244:246]
stock2016_df$十天後[1:10] = stock2017_df$收盤價[237:246]

stock2016_df <- stock2016_df %>%
  mutate("五天後變化" = 五天後 - 收盤價) %>%
  mutate("三天後變化" = 三天後 - 收盤價) %>%
  mutate("十天後變化" = 十天後 - 收盤價) %>%
  mutate("五天後漲" = if_else(五天後變化 >=0, 1, 0)) %>%
  mutate("三天後漲" = if_else(三天後變化 >=0, 1, 0)) %>%
  mutate("十天後漲" = if_else(十天後變化 >=0, 1, 0)) %>%
  view()
```

```{r}
stock2018_df[11:nrow(stock2018_df),] %>%
write_csv(path = "./2018.csv")

stock2017_df %>% write_csv(path = "./2017.csv")
stock2016_df %>% write_csv(path = "./2016.csv")
```